2018-06-21 00:05:15 [ERROR] <class 'pymysql.err.OperationalError'> (ConnectionManager.py line:35)
    Traceback (most recent call last):
      File "F:/work_space/pythonSpace/leiax00/basic/ReplaceTools/server/util/ConnectionManager.py", line 28, in get_cursor
        database=self.config['database'])
      File "F:\work_space\pythonSpace\venv\lib\site-packages\pymysql\__init__.py", line 90, in Connect
        return Connection(*args, **kwargs)
      File "F:\work_space\pythonSpace\venv\lib\site-packages\pymysql\connections.py", line 704, in __init__
        self.connect()
      File "F:\work_space\pythonSpace\venv\lib\site-packages\pymysql\connections.py", line 1005, in connect
        raise exc
    OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 10061] )")
2018-06-21 00:05:15 [WARNING] cursor is None, can not execute sql... (ConnectionManager.py line:47)
